### ISSUE TITLE
[SUGESTÃO] Adicionar ROADMAP das Features no README

### ISSUE THREAD

**Issue by renanrider** [SOS-RS/frontend#231]
# Descrição

Organização das fetures, bugs e pull request.

# Problema encontrado

Descobri o projeto agora e achei bem legal a ideia, porém achei um pouco complicado de localizar o que tem para feito, tendo que verificar em vários lugares e descobrir o status.

# Prioridade
Registre apenas a prioridade ou seriedade do defeito. Um guia:
- Baixa

# Solução proposta

Adicionar um roadmap no README das fetures que foram aprovadas para serem feitas e bugs encontrados
## Roadmap
- ### Features
  - [x] Busca de abrigos por nome
  - [x] Filtro de abrigos por cidade
  - [ ] Filtro de abrigos por status
  - [ ] Filtro de abrigos por categoria
-  ### Bugs
  - [ ] Altura de Navbar divergente entre páginas <a href="https://github.com/SOS-RS/frontend/issues/221" target="_blank">Issue#221</a>

# Ambiente
Github

**Comment by giggio** [comment]
Pessoal, vamos usar o Github projects: https://github.com/orgs/SOS-RS/projects/1
